apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686

  - name: OpenSearch
    isDefault: true
    uid: opensearch
    type: grafana-opensearch-datasource
    access: proxy
    url: https://opensearch:9200
    database: "filebeat-*"
    basicAuth: true
    basicAuthUser: admin
    jsonData:
      database: "filebeat-*"
      flavor: "elasticsearch"
      logLevelField: "log.level"
      logMessageField: "message"
      maxConcurrentShardRequests: 5
      pplEnabled: true
      timeField: "@timestamp"
      tlsSkipVerify: true
      version: "7.10.2"
      dataLinks:
        - datasourceUid: jaeger
          field: "trace.id"
          url: "$${__value.raw}"
    secureJsonData:
      basicAuthPassword: SecretPassw0rd!
