name: Run tests

on:
  push:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install hurl
        uses: gacts/install-hurl@v1

      - name: Run tests
        run: cd tests && ./run.sh && cd -
